---
language: objective-c

before_install:
- brew update

install:
- sudo pip install ansible --quiet
- gem install json
- gem install CFPropertyList

before_script:
- cp tests/stack.yml ~/.stack.yml
- cp tests/galaxy.yml ~/.galaxy.yml

script:
- bash <(curl -s curl -L https://raw.githubusercontent.com/poetic/short-stack/master/install.sh) --skip-short-stack
- bash short-stack
- bash short-stack
- >
  short-stack

  grep -q 'changed=0.*failed=0'
  && (echo 'Idempotence test: pass' && exit 0)
  || (echo 'Idempotence test: fail' && exit 1)

notifications:
  slack:
    secure: cfIOs3ZEoPd0JSRGvkNIWOy55Z8GnRpMHokhGbYtQVxS2RiDE5HeV75E5qv/sxrwcEdNq1okbym4B/ZzK/68zHfhc96Es9uR3xQXtQnrtb5fsrKyuuuV6anJiPP2Lzf+/NEMeUN3r8nbJdLOxkzqxhS0Qc4qVZY6hFP5hPC8/jA=
