---
- name: ensure the ruby json gem is present
  gem: name=json state=present

- name: ensure the ruby CFPropertyList gem is present
  gem: name=CFPropertyList state=present

- name: bind caps lock to ctrl
- action: bind_caps_to_ctrl

- name: Ensure osx configuration
  osx_write: domain={{ item.domain }} key={{ item.key }} value={{ item.value }}
  with_items:
    - { domain: NSGlobalDomain, key: NSNavPanelExpandedStateForSaveMode, value: true }
    - { domain: NSGlobalDomain, key: NSNavPanelExpandedStateForSaveMode2, value: true }
    - { domain: com.apple.LaunchServices, key: LSQuarantine, value: false }
    - { domain: NSGlobalDomain, key: AppleMiniaturizeOnDoubleClick, value: false }
    - { domain: com.apple.dock, key: autohide, value: true }
    - { domain: com.apple.dock, key: autohide-delay, value: 0 }
    - { domain: com.apple.dock, key: showhidden, value: true }
    - { domain: com.apple.finder, key: QuitMenuItem, value: true }
    - { domain: com.apple.finder, key: DSDontWriteNetworkStores, value: true }
    - { domain: com.apple.finder, key: ShowStatusBar, value: true }
    - { domain: com.apple.NetworkBrowser, key: BrowseAllInterfaces, value: true }
    - { domain: com.apple.finder, key: AppleShowAllExtensions, value: true }
    - { domain: com.apple.finder, key: FXEnableExtensionChangeWarning, value: false }
    - { domain: com.apple.driver.AppleBluetoothMultitouch.trackpad, key: Clicking, value: 1 }
    - { domain: com.apple.driver.AppleBluetoothMultitouch.trackpad, key: TrackpadRightClick, value: true }
    - { domain: NSGlobalDomain, key: ApplePressAndHoldEnabled, value: false }
    - { domain: NSGlobalDomain, key: KeyRepeat, value: 0 }
    - { domain: NSGlobalDomain, key: InitialKeyRepeat, value: 6 }
    - { domain: org.webkit.nightly.WebKit, key: StartPageDisabled, value: true }
    - { domain: com.apple.Safari, key: IncludeDevelopMenu, value: true }
    - { domain: com.apple.Safari, key: WebKitDeveloperExtrasEnabledPreferenceKey, value: true }
    - { domain: com.apple.SoftwareUpdate, key: ScheduleFrequency, value: 1 }
    - { domain: NSGlobalDomain, key: com.apple.sound.beep.feedback, value: 0 }
    - { domain: com.apple.finder, key: ShowExternalHardDrivesOnDesktop, value: true }
    - { domain: com.apple.finder, key: ShowMountedServersOnDesktop, value: true }
    - { domain: com.apple.finder, key: ShowRemovableMediaOnDesktop, value: true }

- name: add osx configuration to zsh
  copy: src=osx.zsh dest={{ zshrc_d }}
